name: Test Secrets

on:
  push:
    branches:
      - main

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Print NPMJS_TOKEN secret
        run: echo ${{ secrets.NPMJS_TOKEN }}
